### ISSUE TITLE
Hyperlane Investigation

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#114]
```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/115
- [ ] https://github.com/astriaorg/astria/issues/116
- [ ] https://github.com/astriaorg/astria/issues/117
- [ ] https://github.com/astriaorg/astria/issues/118
- [ ] https://github.com/astriaorg/astria/issues/119
```

**Comment by noot** [comment]
closing due to staleness and in favour of native bridge accounts
