### ISSUE TITLE
composer: containerization and CI

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#121]
```[tasklist]
### Tasks
- [x] define a Dockerfile for the `composer` instance
- [ ] connect to rollup execution node and sequencer instances
- [x] integrate into CI
```

**Comment by SuperFluffy** [comment]
Closed as part of #192
