### ISSUE TITLE
feat: Trusted Builder MVP

### ISSUE THREAD

**Issue by bharath-123** [astriaorg/astria#1322]
This issue tracks the progress and the work required to build the trusted builder MVP

```
### Design work
- [x] Write a design doc: https://www.notion.so/astria-org/Trusted-Block-Builder-MVP-8eba7cd7cbd34e4e90a4adf726879028?pvs=4
```

```
### Astria-Geth changes
- [x] Support returning the included transactions as per the new protobuf changes for ExecuteBlock
- [x] Support simulateOnly mode for ExecuteBlock where we only create a block but do not insert it to the chain
- [x] Support validating BuilderBundlePacket
- [ ] Support validating BuilderBundlePacket signatures
- [x] Support moving transactions deserialized from BuilderBundlePacket to the top of block
```

```
### Composer changes
- [x] Support calling GetCommitmentState
- [x] Support calling ExecuteBlock on the final bundle to be submitted to simulate it
- [x] Support creating the BuilderBundlePacket
- [] Support signing of BuilderBundlePacket
- [x] Support sending the BuilderBundlePacket as a sequence action to sequencer
- [ ] Compute the max bytes of seq actions we can send based on the BuilderBundlePacket fields
- [x] Update blackbox tests of composer to call the execution api.
```

```
### Conductor Changes
- [x] Modify conductor to ensure that it is compatible with the new ExecutionAPI protobuf changes
- [x] Fix the unit tests in conductor post the protobuf changes.
```

```
### Protobuf changes
- [x] Modify ExecuteBlock protobuf to return the included transactions
- [x] Modify ExecuteBlock protobuf to accept a simulateOnly flag which will allow us to only create a block but not add it to the chain
- [x] Create the BuilderBundlePacket protobufs
- [x] Ensure that the Execution API protobuf changes and BuilderBundlePacket protobuf changes are pushed to buf.build
```

```
### Testing
- [x] Test if Astria Geth and Conductor compatible with the Execution API changes by deploying them locally
- [x] Launch the changes in a local cluster and send txs with spamooor
```

┆Issue Number: ENG-671

**Comment by joroshiba** [comment]
This issue is stale because it has been open 45 days with no activity. Remove stale label or this issue
be closed in 7 days.

**Comment by joroshiba** [comment]
This issue was closed because it was stale
