### ISSUE TITLE
Refactor Execution API

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#138]
The current execution API has some naming issues, and isn't fully thought out. It should be redesigned. Working doc to be turned into spec in notion [here](https://www.notion.so/astria-org/Execution-API-Refresh-e9f9777311b0441db39be803291a0f3f?d=ccef5dfd5436481eb4720692cb247fff#6cc2196e59754f0abe3a78b91d47aa0b) 
```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/84
- [ ] https://github.com/astriaorg/astria/issues/205
- [ ] geth: implement new execution API server
- [ ] https://github.com/astriaorg/astria/issues/207
```

**Comment by noot** [comment]
related / possible duplicate of #50

**Comment by jbowen93** [comment]
Possibly related to https://github.com/astriaorg/astria/issues/84
