### ISSUE TITLE
Auctioneer binary scaffolding

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#1534]
┆Issue Number: ENG-824

We will reuse much of the `composer`'s structure in building the `auctioneer`. To start, will add a new binary/crate based on `composer`'s structure that will serve as scaffolding for the `auctioneer`.

```[tasklist]
### Tasks
- [x] Add `auctioneer` crate
- [x] Get rid of unused config variables from composer
- [x] Get rid of unused metrics
- [x] Remove existing `Geth` and `Grpc` collectors
- [x] Remove executor logic
```

**Comment by joroshiba** [comment]
This issue is stale because it has been open 45 days with no activity. Remove stale label or this issue
be closed in 7 days.

**Comment by SuperFluffy** [comment]
Closing this because this is far too granular
