### ISSUE TITLE
Add Optimistic Block Executor logic to Auctioneer

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#1535]
- [ ] Link to system diagram
- [ ] Link to master doc

As per the requirements outlined in the trusted auctioneer MVP design, the `auctioneer` will receive blocks optimistically from the sequencer and pass them to the bundle service for execution. A task to manage this needs to be implemented.

The `OptimisticBlockExecutor` will:

```[tasklist]
### Tasks
- [x] Subscribe to the `OptimisticBlockStream` and `BlockCommitment` streams from the sequencer
- [x] Set up the bidirectional streams with the `BundleService` in Geth
- [x] Convert `FilteredSequencerBlock` received from the `OptimisticBlockStream` to `BaseBlock` and push to the `BundleService` for optimistic execution
- [x] Process the optimistic execution results streamed from the `BundleService` to trigger the start the auction
```

**Comment by joroshiba** [comment]
This issue is stale because it has been open 45 days with no activity. Remove stale label or this issue
be closed in 7 days.

**Comment by joroshiba** [comment]
This issue was closed because it was stale
