### ISSUE TITLE
composer: smoke tests

### ISSUE THREAD

**Issue by dereksione** [astriaorg/astria#194]
Write smoke tests for composer that replicates how composer would interact with sequencer-relayer and the rollup transaction pools in an e2e pipeline

# Subtasks

- [x] Mock a `Provider` that replicates behavior of a Provider that fetched data from a rollup transaction pool
- [x] Mock `Sequencer-Relayer` client such that the composer can react to responses given by it
- [ ] Replicate possible scenarios that might occur on an e2e pipeline

**Comment by itamarreif** [comment]
#192 includes these
