### ISSUE TITLE
Composer: Infrastructure for arbitrary number of collectors to stream data to composer

### ISSUE THREAD

**Issue by dereksione** [astriaorg/astria#214]
Right now, we can only collecting pending tx data from one rollup client (eth), but we want to allow any arbitrary number of rollups to be added to the pipeline, and thus the composer to be able to easily spawn up new collectors that can start streaming data to the composer pipeline.

# Subtasks

- [x] Add a generic provider wrapper type that isn't tied to eth provider implementations
- [x] Collectors should be generic over provider
- [x] Arbitrary number of collectors should be streaming data to the same outgoing channel 
- [ ] Testing suite that ensure that there are no backpressure bottlenecks
