### ISSUE TITLE
composer: handle undesirable provider behavior

### ISSUE THREAD

**Issue by dereksione** [astriaorg/astria#232]
## Motivation

The current architecture of the composer (i.e. split up into the collector, the bundler and executor) makes it such that only the collector interfaces with the outside world. It collects providers that adhere to a common interface defined that forwards to it all pending transactions that the provider receives from it's own subscription stream from a rollup client. Since the expected behavior is to constantly receive a stream of pending transactions from each provider, any deviation from this would require deliberate handling. For instance, if a provider has been unresponsive for a significant chunk of time, it is not desirable for the collector to keep ascribing resources to maintaining its state and connections (See #16)

## Subtasks

- [ ] Identify categories of undesirable behaviors that need to be handled
- [ ] Have a clear strategy on how to deal with already expected undesirable behavior
- [ ] Have a clear strategy on how to deal with an unforeseen undesirable behavior (i.e. have a default foolproof handling strategy)
- [ ] Have robust logging to allow tracking of unexpected behavior
- [ ] Smoke tests for all the expected undesirable behavior
- [ ] Have smoke tests integrated into the CI pipeline to ensure that internal logic level changes don't break the previously expected behavior

**Comment by SuperFluffy** [comment]
The issue description makes a lot of sense, but is out of context because none of the behavior that needs to be fixed is currently implemented.

Happy to reopen this at a future point.
