### ISSUE TITLE
composer: separate searcher and builder binaries

### ISSUE THREAD

**Issue by dereksione** [astriaorg/astria#234]
## Motivation

In the long term, the composer should be split up into two separate binaries - the `Searcher` and the `Builder`, with the Searcher collecting rollup transactions, executing some opaque MEV strategy and in the process creating Astria-sequencer transactions that have one or more rollup transactions embedded within them. They then pass this off to the block-builder (through some economically competitive interface) that then combine these transactions into an Astria-sequencer block that they then auction off to the Block Proposers.

Since these two responsibilities are independent from one another, we have to accommodate for use cases where an actor wants to do one but not the other. 

## Subtasks

- [ ] The Searcher and Builder are split up into separate binary crates that act independently
- [ ] Smoke tests for each of the binaries
- [ ] Integration tests that ensure desired interactions between the two
- [ ] Ensure that both the Searcher and the Builder combined continue to perform the same tasks as the integrated composer
