### ISSUE TITLE
Configuration Standards

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#240]
Standardize our configuration across services & binaries.

```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/241
- [ ] https://github.com/astriaorg/astria/issues/242
- [ ] https://github.com/astriaorg/astria/issues/243
- [ ] https://github.com/astriaorg/astria/issues/244
- [ ] https://github.com/astriaorg/astria/issues/245
```
