### ISSUE TITLE
repo organizational structure improvements

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#266]
```
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/267
- [ ] https://github.com/astriaorg/astria/issues/268
- [ ] release pathway
- [ ] https://github.com/astriaorg/astria/issues/274
```
