### ISSUE TITLE
Docathon: specs for components.

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#297]
We are huddled writing docs in Boulder.

```
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/298
- [ ] https://github.com/astriaorg/astria/issues/299
- [ ] https://github.com/astriaorg/astria/issues/300
- [ ] https://github.com/astriaorg/astria/issues/301
```

**Comment by joroshiba** [comment]
closing because we created docs
