### ISSUE TITLE
conductor: update and add logging/tracing information

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#313]
# Summary

Currently the Conductor has a decent amount of logging and tracing calls throughout, this issue is for identifying what calls should actually exist, and add in additional calls where they are missing.

# TODO
- [x] Identify what events should be logged
- [x] Add in missing calls
- [x] Update existing calls

Related to #14 #231 
```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/231
- [ ] https://github.com/astriaorg/astria/issues/14
```

**Comment by sambukowski** [comment]
Here is a doc that loosely tracks the state of adding tracing to Conductor: https://www.notion.so/astria-org/conductor-logging-tracing-ee2950559ed14ea09693d50364102e3c
It is a little out of data because of @SuperFluffy's pr here: https://github.com/astriaorg/astria/pull/455
