### ISSUE TITLE
Extract sequencer APIs as protobuf and implemented public interfaces in terms of these

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#356]
Various types are currently exchanged between Astria Services as JSON serialized text, where they should be defined and encoded as protobufs.

The main types are (possibly in addition to some smaller ones I overlooked): `SequencerBlockData`, `InclusionProof` `SequencerNamespaceData`, `RollupNamespaceData`.

`astria.sequencer.v1alpha1` actually contains protobuf definitions of these, but they were never used and are by now no longer compatible with the Rust definitions.

The Rust definitions should be extracted as Protobufs, and sequencer, sequencer-relayer, and conductor implemented in terms of them.

```[tasklist]
### Tasks
- [x] Define protobufs: https://github.com/astriaorg/astria/pull/443
- [x] Update chain ID to be 32 bytes: https://github.com/astriaorg/astria/pull/436
- [x] Implemented a rust-native API for the generated rust protobuf types: https://github.com/astriaorg/astria/pull/444
- [x] Implement services in terms of these
```

**Comment by SuperFluffy** [comment]
This has all been implement via #395
