### ISSUE TITLE
Conductor: Rollup Sync Implementation

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#471]
Possible places that historical data can be synced from are the sequencer and the DA.

Currently sync a new rollup on Astria only syncs from the sequencer.

Possible configurations:
- Only from Sequencer
- Only from DA
- Both
- Config setting to choose one of the above

Additional thought need to be given to what gets implemented here.
```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/470
- [ ] https://github.com/astriaorg/astria/pull/455
- [ ] https://github.com/astriaorg/astria/issues/473
- [ ] https://github.com/astriaorg/astria/issues/323
```

**Comment by noot** [comment]
closing as completed
