### ISSUE TITLE
composer: logging tracking issue

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#472]
A rolling to-do list of things that need to be logged in the `composer`:

```
### Tasks
- [ ] Mapping between rollup transactions to sequencer transactions
```

**Comment by itamarreif** [comment]
from #409:
- [ ] log when a tx is dropped due to backpressure

from #599:
- [ ] log when a tx is dropped due to being too big
