### ISSUE TITLE
Conductor: Block retrieval and Ordering verification 

### ISSUE THREAD

**Issue by sambukowski** [astriaorg/astria#475]
Additional work needs to be done to add verification and finalize how blocks are pulled from the Sequencer and DA, into the Conductor.
```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/465
- [ ] https://github.com/astriaorg/astria/issues/464
- [ ] https://github.com/astriaorg/astria/issues/323
```

**Comment by noot** [comment]
closing as completed
