### ISSUE TITLE
refactor sequencer-relayer

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#60]
```[tasklist]
### Tasks
- [x] allow configuring from environment variables (closed in #59)
- [ ] https://github.com/astriaorg/astria/issues/85
- [ ] https://github.com/astriaorg/astria/issues/86
- [ ] https://github.com/astriaorg/astria/issues/87
```

**Comment by emhane** [comment]
can we use https://github.com/informalsystems/hermes ?
