### ISSUE TITLE
Replace Metro w/ Rust Sequencer

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#75]
```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/64
- [ ] https://github.com/astriaorg/astria/issues/65
- [ ] https://github.com/astriaorg/astria/issues/67
- [ ] https://github.com/astriaorg/astria/issues/99
- [ ] https://github.com/astriaorg/astria/issues/110
- [ ] https://github.com/astriaorg/astria/issues/108
```
