### ISSUE TITLE
Composer Enhancements

### ISSUE THREAD

**Issue by bharath-123** [astriaorg/astria#795]
This issue tracks the progess of Enhancements of Composer to be mainnet ready.

```
### Tasks
- [x] Re-name Collectors to GethCollector to distinguish b/w the various collector. (Done in https://github.com/astriaorg/astria/pull/792)
- [x] Move Executor and Collector tasks to the Composer (Done in https://github.com/astriaorg/astria/pull/796)
- [x] Add the gRPC collector (done in https://github.com/astriaorg/astria/pull/784)
- [ ] Add signal handling for graceful shutdown of the gRPC Collector, GethCollector and Executor (Being worked on in https://github.com/astriaorg/astria/pull/854)
- [ ] Remove the API Server in favour of using the gRPC server for healthchecks.
- [ ] Add logging and metrics
- [ ] Add tracing logic for rollup transaction to sequencer transaction tracking.
```
