### ISSUE TITLE
Tracker for `state_ext` unit tests 

### ISSUE THREAD

**Issue by Lilyjjo** [astriaorg/astria#866]
Tracker for adding state_ext unit tests per file:

```[tasklist]
### Progress
- [x] astria-sequencer/src/state_ext.rs: [PR](https://github.com/astriaorg/astria/pull/858)
- [x] astria-sequencer/src/accounts/state_ext.rs
- [x] astria-sequencer/src/asset/state_ext.rs
- [x] astria-sequencer/src/authority/state_ext.rs
- [x] astria-sequencer/src/bridge/state_ext.rs
- [x] astria-sequencer/src/ibc/state_ext.rs
```
