### ISSUE TITLE
refactor conductor

### ISSUE THREAD

**Issue by SuperFluffy** [astriaorg/astria#90]
```[tasklist]
### Tasks
- [ ] https://github.com/astriaorg/astria/issues/92
- [ ] https://github.com/astriaorg/astria/issues/95
- [ ] https://github.com/astriaorg/astria/issues/381
- [ ] https://github.com/astriaorg/astria/issues/94
```
